name: patchtst
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy<2
  # - plotly
  # - scipy
  # - numba
  - pytorch==1.13.1
  - pytorch-cuda==11.6
  - scikit-learn
  - pyyaml
  - pyarrow
  - boto3
  - requests
  # - pip
  # - pip:
  #   - vqf==2.0.0